package vista;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.LinearGradientPaint;
import java.awt.RenderingHints;
import java.awt.geom.Point2D;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 *
 * @author xDoble_Jx
 */
public class PMenu extends JPanel {

    private VPrincipal vPrincipal;

    /**
     * Creates new form PMenu
     */
    public PMenu() {
        initComponents();
        setOpaque(false);

    }

    public void setPadre(VPrincipal vPrincipal) {
        this.vPrincipal = vPrincipal;
    }


    /*
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g.create();

        int width = getWidth();
        int height = getHeight();

        // Dibujar fondo redondo
        RoundRectangle2D roundRect = new RoundRectangle2D.Double(0, 0, width, height, 15, 15);

        g2d.setClip(roundRect);

        // Dibujar imagen de fondo
        String rutaProyecto = System.getProperty("user.dir");
        String imagen = rutaProyecto + "\\src\\recursos\\iconos_pantalla\\pnlMenu.png";

        Image backgroundImage = null;
        try {
            backgroundImage = ImageIO.read(new File(imagen));
        } catch (IOException ex) {
            Logger.getLogger(PMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (backgroundImage != null) {
            g2d.drawImage(backgroundImage, 0, 0, width, height, null);
        } else {
            g2d.setColor(Color.WHITE);
            g2d.fillRect(0, 0, width, height);
        }

        g2d.dispose();
    }
     */
    @Override
    public void paint(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.dispose();
        super.paint(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblLetrasLogo = new javax.swing.JLabel();
        pnlUsuario = new recursos.LookVentana.RoundPanel();
        imgUsuario = new recursos.LookVentana.ImageAvatar();
        lblUsuarioTxt = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnInicio = new recursos.LookVentana.ButtonMenu();
        btnRuleta = new recursos.LookVentana.ButtonMenu();
        btnTragaperra = new recursos.LookVentana.ButtonMenu();
        btnQuinela = new recursos.LookVentana.ButtonMenu();
        btnCaballos = new recursos.LookVentana.ButtonMenu();
        btnMoreOrLess = new recursos.LookVentana.ButtonMenu();
        btnBlackjack = new recursos.LookVentana.ButtonMenu();
        btnCuenta = new recursos.LookVentana.ButtonMenu();
        btnSalir = new recursos.LookVentana.ButtonMenu();

        setBackground(new java.awt.Color(49, 51, 53));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/logo.png"))); // NOI18N

        pnlUsuario.setBackground(new java.awt.Color(59, 61, 63));

        imgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Usuario/iconoDavid.png"))); // NOI18N

        lblUsuarioTxt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblUsuarioTxt.setForeground(new java.awt.Color(227, 227, 227));
        lblUsuarioTxt.setText("USUARIO");

        lblUsuario.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(227, 227, 227));
        lblUsuario.setText("Jason");

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(imgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuarioTxt)
                    .addComponent(lblUsuario))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsuarioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUsuarioLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblUsuarioTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsuario)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/btnCasino.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setFocusPainted(false);
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnRuleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/btnRuleta.png"))); // NOI18N
        btnRuleta.setText("Ruleta");
        btnRuleta.setFocusPainted(false);
        btnRuleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRuleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRuletaActionPerformed(evt);
            }
        });

        btnTragaperra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/btnTragaperra.png"))); // NOI18N
        btnTragaperra.setText("Tragaperra");
        btnTragaperra.setFocusPainted(false);
        btnTragaperra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTragaperra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTragaperraActionPerformed(evt);
            }
        });

        btnQuinela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/btnQuinela.png"))); // NOI18N
        btnQuinela.setText("Quinela");
        btnQuinela.setFocusPainted(false);
        btnQuinela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuinela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuinelaActionPerformed(evt);
            }
        });

        btnCaballos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/btnCaballo.png"))); // NOI18N
        btnCaballos.setText("Caballos");
        btnCaballos.setFocusPainted(false);
        btnCaballos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCaballos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaballosActionPerformed(evt);
            }
        });

        btnMoreOrLess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/btnMoreOrLess.png"))); // NOI18N
        btnMoreOrLess.setText("More Or Less");
        btnMoreOrLess.setFocusPainted(false);
        btnMoreOrLess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMoreOrLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreOrLessActionPerformed(evt);
            }
        });

        btnBlackjack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/btnBlackjack.png"))); // NOI18N
        btnBlackjack.setText("Blackjack");
        btnBlackjack.setFocusPainted(false);
        btnBlackjack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBlackjack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlackjackActionPerformed(evt);
            }
        });

        btnCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/btnCuenta.png"))); // NOI18N
        btnCuenta.setText("Cuenta");
        btnCuenta.setFocusPainted(false);
        btnCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/btnSalir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBlackjack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMoreOrLess, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCaballos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRuleta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addGap(18, 18, 18)
                        .addComponent(lblLetrasLogo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTragaperra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuinela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo)
                    .addComponent(lblLetrasLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnRuleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnTragaperra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnQuinela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnCaballos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnMoreOrLess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnBlackjack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        System.out.println("-- INICIO --");
        vPrincipal.panelMain.show(0);

    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnRuletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRuletaActionPerformed
        System.out.println("-- RULETA --");
        vPrincipal.panelMain.show(1);
    }//GEN-LAST:event_btnRuletaActionPerformed

    private void btnTragaperraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTragaperraActionPerformed
        System.out.println("-- TRAGAPERRAS --");
        vPrincipal.panelMain.show(2);
    }//GEN-LAST:event_btnTragaperraActionPerformed

    private void btnQuinelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuinelaActionPerformed
        System.out.println("-- INICIO --");
        vPrincipal.panelMain.show(3);
    }//GEN-LAST:event_btnQuinelaActionPerformed

    private void btnCaballosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaballosActionPerformed
        System.out.println("-- CABALLOS --");
        vPrincipal.panelMain.show(4);
    }//GEN-LAST:event_btnCaballosActionPerformed

    private void btnMoreOrLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreOrLessActionPerformed
        System.out.println("-- MOREORLESS --");
        vPrincipal.panelMain.show(5);
    }//GEN-LAST:event_btnMoreOrLessActionPerformed

    private void btnBlackjackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlackjackActionPerformed
        System.out.println("-- BLACKJACK --");
        vPrincipal.panelMain.show(6);
    }//GEN-LAST:event_btnBlackjackActionPerformed

    private void btnCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaActionPerformed
        System.out.println("-- CUENTA --");
        vPrincipal.panelMain.show(7);
    }//GEN-LAST:event_btnCuentaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.out.println("-- SALIR --");
        vPrincipal.salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private recursos.LookVentana.ButtonMenu btnBlackjack;
    private recursos.LookVentana.ButtonMenu btnCaballos;
    private recursos.LookVentana.ButtonMenu btnCuenta;
    private recursos.LookVentana.ButtonMenu btnInicio;
    private recursos.LookVentana.ButtonMenu btnMoreOrLess;
    private recursos.LookVentana.ButtonMenu btnQuinela;
    private recursos.LookVentana.ButtonMenu btnRuleta;
    private recursos.LookVentana.ButtonMenu btnSalir;
    private recursos.LookVentana.ButtonMenu btnTragaperra;
    private recursos.LookVentana.ImageAvatar imgUsuario;
    private javax.swing.JLabel lblLetrasLogo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioTxt;
    private recursos.LookVentana.RoundPanel pnlUsuario;
    // End of variables declaration//GEN-END:variables

}
