/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.util.Map;
import javax.swing.Timer;

/**
 *
 * @author xDoble_Jx
 */
public class PRuleta extends javax.swing.JPanel {

    private Map<String, Integer> apuestas;
    private float cuota;
    private int cant;

    /**
     * Creates new form PRuleta
     */
    public PRuleta() {
        initComponents();
    }

    @Override
    public void paint(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.dispose();
        super.paint(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ruleta = new recursos.LookVentana.RoundPanel();
        imgRuleta = new javax.swing.JLabel();
        gestion = new recursos.LookVentana.RoundPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        roundPanel1 = new recursos.LookVentana.RoundPanel();
        ruleta1 = new recursos.LookVentana.RoundPanel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        b9 = new javax.swing.JLabel();
        b10 = new javax.swing.JLabel();
        b11 = new javax.swing.JLabel();
        b12 = new javax.swing.JLabel();
        b13 = new javax.swing.JLabel();
        b14 = new javax.swing.JLabel();
        b15 = new javax.swing.JLabel();
        b16 = new javax.swing.JLabel();
        b17 = new javax.swing.JLabel();
        b18 = new javax.swing.JLabel();
        b19 = new javax.swing.JLabel();
        b20 = new javax.swing.JLabel();
        b21 = new javax.swing.JLabel();
        b22 = new javax.swing.JLabel();
        b23 = new javax.swing.JLabel();
        b24 = new javax.swing.JLabel();
        b25 = new javax.swing.JLabel();
        b26 = new javax.swing.JLabel();
        b27 = new javax.swing.JLabel();
        b28 = new javax.swing.JLabel();
        b29 = new javax.swing.JLabel();
        b30 = new javax.swing.JLabel();
        b31 = new javax.swing.JLabel();
        b32 = new javax.swing.JLabel();
        b33 = new javax.swing.JLabel();
        b34 = new javax.swing.JLabel();
        b35 = new javax.swing.JLabel();
        b36 = new javax.swing.JLabel();
        b0 = new javax.swing.JLabel();
        a1_12 = new javax.swing.JLabel();
        a13_24 = new javax.swing.JLabel();
        a25_36 = new javax.swing.JLabel();
        a1_18 = new javax.swing.JLabel();
        aPar = new javax.swing.JLabel();
        aRojo = new javax.swing.JLabel();
        aNegro = new javax.swing.JLabel();
        aImpar = new javax.swing.JLabel();
        a19_36 = new javax.swing.JLabel();
        a3fila = new javax.swing.JLabel();
        a2fila = new javax.swing.JLabel();
        a1fila = new javax.swing.JLabel();
        imgBotonesRuleta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(21, 21, 21));

        ruleta.setBackground(new java.awt.Color(49, 51, 53));

        imgRuleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgRuleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/ruleta.png"))); // NOI18N
        imgRuleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgRuletaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ruletaLayout = new javax.swing.GroupLayout(ruleta);
        ruleta.setLayout(ruletaLayout);
        ruletaLayout.setHorizontalGroup(
            ruletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgRuleta, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
        ruletaLayout.setVerticalGroup(
            ruletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgRuleta, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        gestion.setBackground(new java.awt.Color(49, 51, 53));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/ficha1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/ficha5.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        jLabel3.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/ficha10.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        jLabel4.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/ficha500.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        jLabel5.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/ficha100.png"))); // NOI18N
        jLabel6.setText("jLabel2");
        jLabel6.setPreferredSize(new java.awt.Dimension(32, 32));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/ficha50.png"))); // NOI18N
        jLabel7.setText("jLabel2");
        jLabel7.setPreferredSize(new java.awt.Dimension(32, 32));

        roundPanel1.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout gestionLayout = new javax.swing.GroupLayout(gestion);
        gestion.setLayout(gestionLayout);
        gestionLayout.setHorizontalGroup(
            gestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        gestionLayout.setVerticalGroup(
            gestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(gestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(gestionLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ruleta1.setBackground(new java.awt.Color(49, 51, 53));
        ruleta1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        ruleta1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 70, 80));

        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });
        ruleta1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 70, 80));

        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
        });
        ruleta1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 70, 80));

        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b4MouseClicked(evt);
            }
        });
        ruleta1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 60, 80));

        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b5MouseClicked(evt);
            }
        });
        ruleta1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, 80));

        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b6MouseClicked(evt);
            }
        });
        ruleta1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 60, 80));

        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b7MouseClicked(evt);
            }
        });
        ruleta1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 60, 80));

        b8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b8MouseClicked(evt);
            }
        });
        ruleta1.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 60, 70));

        b9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b9MouseClicked(evt);
            }
        });
        ruleta1.add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 60, 80));

        b10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b10MouseClicked(evt);
            }
        });
        ruleta1.add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 60, 80));

        b11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b11MouseClicked(evt);
            }
        });
        ruleta1.add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 60, 80));

        b12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b12MouseClicked(evt);
            }
        });
        ruleta1.add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 60, 80));

        b13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b13MouseClicked(evt);
            }
        });
        ruleta1.add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 60, 80));

        b14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b14MouseClicked(evt);
            }
        });
        ruleta1.add(b14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 60, 80));

        b15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b15MouseClicked(evt);
            }
        });
        ruleta1.add(b15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 60, 80));

        b16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b16MouseClicked(evt);
            }
        });
        ruleta1.add(b16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 60, 80));

        b17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b17MouseClicked(evt);
            }
        });
        ruleta1.add(b17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 60, 80));

        b18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b18MouseClicked(evt);
            }
        });
        ruleta1.add(b18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 60, 80));

        b19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b19MouseClicked(evt);
            }
        });
        ruleta1.add(b19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 60, 80));

        b20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b20MouseClicked(evt);
            }
        });
        ruleta1.add(b20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 60, 80));

        b21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b21MouseClicked(evt);
            }
        });
        ruleta1.add(b21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 60, 80));

        b22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b22MouseClicked(evt);
            }
        });
        ruleta1.add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 60, 80));

        b23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b23MouseClicked(evt);
            }
        });
        ruleta1.add(b23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 60, 80));

        b24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b24MouseClicked(evt);
            }
        });
        ruleta1.add(b24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 60, 80));

        b25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b25MouseClicked(evt);
            }
        });
        ruleta1.add(b25, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 60, 80));

        b26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b26MouseClicked(evt);
            }
        });
        ruleta1.add(b26, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 60, 80));

        b27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b27MouseClicked(evt);
            }
        });
        ruleta1.add(b27, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 60, 80));

        b28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b28MouseClicked(evt);
            }
        });
        ruleta1.add(b28, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 60, 80));

        b29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b29MouseClicked(evt);
            }
        });
        ruleta1.add(b29, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 60, 80));

        b30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b30MouseClicked(evt);
            }
        });
        ruleta1.add(b30, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 60, 80));

        b31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b31MouseClicked(evt);
            }
        });
        ruleta1.add(b31, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 60, 80));

        b32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b32MouseClicked(evt);
            }
        });
        ruleta1.add(b32, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 60, 80));

        b33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b33MouseClicked(evt);
            }
        });
        ruleta1.add(b33, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 60, 80));

        b34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b34MouseClicked(evt);
            }
        });
        ruleta1.add(b34, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 60, 80));

        b35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b35MouseClicked(evt);
            }
        });
        ruleta1.add(b35, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 60, 80));

        b36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b36MouseClicked(evt);
            }
        });
        ruleta1.add(b36, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 60, 80));

        b0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b0MouseClicked(evt);
            }
        });
        ruleta1.add(b0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 250));

        a1_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1_12MouseClicked(evt);
            }
        });
        ruleta1.add(a1_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 260, 60));

        a13_24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a13_24MouseClicked(evt);
            }
        });
        ruleta1.add(a13_24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 260, 60));

        a25_36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a25_36MouseClicked(evt);
            }
        });
        ruleta1.add(a25_36, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 260, 60));

        a1_18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1_18MouseClicked(evt);
            }
        });
        ruleta1.add(a1_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 130, 60));

        aPar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aParMouseClicked(evt);
            }
        });
        ruleta1.add(aPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 130, 60));

        aRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aRojoMouseClicked(evt);
            }
        });
        ruleta1.add(aRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 130, 60));

        aNegro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aNegroMouseClicked(evt);
            }
        });
        ruleta1.add(aNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 130, 60));

        aImpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aImparMouseClicked(evt);
            }
        });
        ruleta1.add(aImpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 130, 60));

        a19_36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a19_36MouseClicked(evt);
            }
        });
        ruleta1.add(a19_36, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 130, 60));

        a3fila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a3filaMouseClicked(evt);
            }
        });
        ruleta1.add(a3fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, 60, 80));

        a2fila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2filaMouseClicked(evt);
            }
        });
        ruleta1.add(a2fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 70, 80));

        a1fila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1filaMouseClicked(evt);
            }
        });
        ruleta1.add(a1fila, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 70, 80));

        imgBotonesRuleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/botones ruleta.png"))); // NOI18N
        ruleta1.add(imgBotonesRuleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ruleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ruleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ruleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(ruleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        apuestas.put("1", cant);
    }//GEN-LAST:event_b1MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        apuestas.put("2", cant);
    }//GEN-LAST:event_b2MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
        apuestas.put("3", cant);
    }//GEN-LAST:event_b3MouseClicked

    private void b5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseClicked
        apuestas.put("5", cant);
    }//GEN-LAST:event_b5MouseClicked

    private void b6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseClicked
        apuestas.put("6", cant);
    }//GEN-LAST:event_b6MouseClicked

    private void b7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseClicked
        apuestas.put("7", cant);
    }//GEN-LAST:event_b7MouseClicked

    private void b8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseClicked
        apuestas.put("8", cant);
    }//GEN-LAST:event_b8MouseClicked

    private void b9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseClicked
        apuestas.put("9", cant);
    }//GEN-LAST:event_b9MouseClicked

    private void b10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b10MouseClicked
        apuestas.put("10", cant);
    }//GEN-LAST:event_b10MouseClicked

    private void b11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b11MouseClicked
        apuestas.put("11", cant);
    }//GEN-LAST:event_b11MouseClicked

    private void b12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b12MouseClicked
        apuestas.put("12", cant);
    }//GEN-LAST:event_b12MouseClicked

    private void b13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b13MouseClicked
        apuestas.put("13", cant);
    }//GEN-LAST:event_b13MouseClicked

    private void b14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b14MouseClicked
        apuestas.put("14", cant);
    }//GEN-LAST:event_b14MouseClicked

    private void b15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b15MouseClicked
        apuestas.put("15", cant);
    }//GEN-LAST:event_b15MouseClicked

    private void b16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b16MouseClicked
        apuestas.put("16", cant);
    }//GEN-LAST:event_b16MouseClicked

    private void b17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b17MouseClicked
        apuestas.put("17", cant);
    }//GEN-LAST:event_b17MouseClicked

    private void b18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b18MouseClicked
        apuestas.put("18", cant);
    }//GEN-LAST:event_b18MouseClicked

    private void b19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b19MouseClicked
        apuestas.put("19", cant);
    }//GEN-LAST:event_b19MouseClicked

    private void b20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b20MouseClicked
        apuestas.put("20", cant);
    }//GEN-LAST:event_b20MouseClicked

    private void b21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b21MouseClicked
        apuestas.put("21", cant);
    }//GEN-LAST:event_b21MouseClicked

    private void b22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b22MouseClicked
        apuestas.put("22", cant);
    }//GEN-LAST:event_b22MouseClicked

    private void b23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b23MouseClicked
        apuestas.put("23", cant);
    }//GEN-LAST:event_b23MouseClicked

    private void b24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b24MouseClicked
        apuestas.put("24", cant);
    }//GEN-LAST:event_b24MouseClicked

    private void b25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b25MouseClicked
        apuestas.put("25", cant);
    }//GEN-LAST:event_b25MouseClicked

    private void b26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b26MouseClicked
        apuestas.put("26", cant);
    }//GEN-LAST:event_b26MouseClicked

    private void b27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b27MouseClicked
        apuestas.put("27", cant);
    }//GEN-LAST:event_b27MouseClicked

    private void b28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b28MouseClicked
        apuestas.put("28", cant);
    }//GEN-LAST:event_b28MouseClicked

    private void b29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b29MouseClicked
        apuestas.put("29", cant);
    }//GEN-LAST:event_b29MouseClicked

    private void b30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b30MouseClicked
        apuestas.put("30", cant);
    }//GEN-LAST:event_b30MouseClicked

    private void b31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b31MouseClicked
        apuestas.put("31", cant);
    }//GEN-LAST:event_b31MouseClicked

    private void b32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b32MouseClicked
        apuestas.put("32", cant);
    }//GEN-LAST:event_b32MouseClicked

    private void b33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b33MouseClicked
        apuestas.put("33", cant);
    }//GEN-LAST:event_b33MouseClicked

    private void b34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b34MouseClicked
        apuestas.put("34", cant);
    }//GEN-LAST:event_b34MouseClicked

    private void b35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b35MouseClicked
        apuestas.put("35", cant);
    }//GEN-LAST:event_b35MouseClicked

    private void b36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b36MouseClicked
        apuestas.put("36", cant);
    }//GEN-LAST:event_b36MouseClicked

    private void b0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b0MouseClicked
        apuestas.put("0", cant);
    }//GEN-LAST:event_b0MouseClicked

    private void a1_12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1_12MouseClicked
        apuestas.put("franja 1-12", cant);
    }//GEN-LAST:event_a1_12MouseClicked

    private void a13_24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a13_24MouseClicked
        apuestas.put("franja 13-24", cant);
    }//GEN-LAST:event_a13_24MouseClicked

    private void a25_36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a25_36MouseClicked
        apuestas.put("franja 25-36", cant);
    }//GEN-LAST:event_a25_36MouseClicked

    private void a1_18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1_18MouseClicked
        apuestas.put("franja 1-18", cant);
    }//GEN-LAST:event_a1_18MouseClicked

    private void aParMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aParMouseClicked
        apuestas.put("par", cant);
    }//GEN-LAST:event_aParMouseClicked

    private void aRojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aRojoMouseClicked
        apuestas.put("rojo", cant);
    }//GEN-LAST:event_aRojoMouseClicked

    private void aNegroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aNegroMouseClicked
        apuestas.put("negro", cant);
    }//GEN-LAST:event_aNegroMouseClicked

    private void aImparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aImparMouseClicked
        apuestas.put("impar", cant);
    }//GEN-LAST:event_aImparMouseClicked

    private void a19_36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a19_36MouseClicked
        apuestas.put("franja 19-36", cant);
    }//GEN-LAST:event_a19_36MouseClicked

    private void a3filaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3filaMouseClicked
        apuestas.put("fila3", cant);
    }//GEN-LAST:event_a3filaMouseClicked

    private void a2filaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2filaMouseClicked
        apuestas.put("fila2", cant);
    }//GEN-LAST:event_a2filaMouseClicked

    private void a1filaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1filaMouseClicked
        apuestas.put("fila1", cant);
    }//GEN-LAST:event_a1filaMouseClicked

    private void b4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseClicked
        apuestas.put("4", cant);
    }//GEN-LAST:event_b4MouseClicked

    private void imgRuletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgRuletaMouseClicked

    }//GEN-LAST:event_imgRuletaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a13_24;
    private javax.swing.JLabel a19_36;
    private javax.swing.JLabel a1_12;
    private javax.swing.JLabel a1_18;
    private javax.swing.JLabel a1fila;
    private javax.swing.JLabel a25_36;
    private javax.swing.JLabel a2fila;
    private javax.swing.JLabel a3fila;
    private javax.swing.JLabel aImpar;
    private javax.swing.JLabel aNegro;
    private javax.swing.JLabel aPar;
    private javax.swing.JLabel aRojo;
    private javax.swing.JLabel b0;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b10;
    private javax.swing.JLabel b11;
    private javax.swing.JLabel b12;
    private javax.swing.JLabel b13;
    private javax.swing.JLabel b14;
    private javax.swing.JLabel b15;
    private javax.swing.JLabel b16;
    private javax.swing.JLabel b17;
    private javax.swing.JLabel b18;
    private javax.swing.JLabel b19;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b20;
    private javax.swing.JLabel b21;
    private javax.swing.JLabel b22;
    private javax.swing.JLabel b23;
    private javax.swing.JLabel b24;
    private javax.swing.JLabel b25;
    private javax.swing.JLabel b26;
    private javax.swing.JLabel b27;
    private javax.swing.JLabel b28;
    private javax.swing.JLabel b29;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b30;
    private javax.swing.JLabel b31;
    private javax.swing.JLabel b32;
    private javax.swing.JLabel b33;
    private javax.swing.JLabel b34;
    private javax.swing.JLabel b35;
    private javax.swing.JLabel b36;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private recursos.LookVentana.RoundPanel gestion;
    private javax.swing.JLabel imgBotonesRuleta;
    private javax.swing.JLabel imgRuleta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private recursos.LookVentana.RoundPanel roundPanel1;
    private recursos.LookVentana.RoundPanel ruleta;
    private recursos.LookVentana.RoundPanel ruleta1;
    // End of variables declaration//GEN-END:variables
}
