/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import clases.Tarjeta;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/**
 *
 * @author xDoble_Jx
 */
public class TarjetaDeCredito extends javax.swing.JPanel {

    private String numTarjeta;
    private LocalDate fech_cadTarjeta;
    private int csvTarjeta;
    private int pinTarjeta;

    private Tarjeta tar;

    /**
     * Creates new form TarjetaDeCredito
     */
    public TarjetaDeCredito(Tarjeta tar) {
        this.tar = tar;
        initComponents();

        if (tar == null) {
            txtNum.setEditable(true);
            txtFecha_cad.setEditable(true);
            txtCsv.setEditable(true);

            spNumero.setVisible(true);
            spFecha_cad.setVisible(true);
            spCsv.setVisible(true);
        } else {
            txtNum.setText(tar.getNum_tarjeta());
            txtNum.setText(String.format("%02d", tar.getFecha_cad().getMonthValue()) + "/" + tar.getFecha_cad().getYear());
            txtNum.setText(tar.getCsv() + "");
        }
    }

    public boolean comprobarNumero() {
        String numS = txtNum.getText().replaceAll("\\s+", "");

        System.out.println(numS);
        try {

            if (numS.length() != 16) {
                spNumero.setForeground(new Color(204, 0, 0));
                System.out.println("no 16 caracteres");
                return false;
            }

            long num = Long.parseLong(numS);

        } catch (NumberFormatException e) {
            System.out.println("no numero");
            spNumero.setForeground(new Color(204, 0, 0));
            return false;
        }

        spNumero.setForeground(new Color(48, 170, 63));
        numTarjeta = numS.replaceAll("(.{4})(?!$)", "$1 ");
        txtNum.setText(numS.replaceAll("(.{4})(?!$)", "$1   "));

        return true;
    }

    public boolean comprobarFecha() {
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("dd/MM/yy");

        try {
            fech_cadTarjeta = LocalDate.parse("01/" + txtFecha_cad.getText(), formateador);

        } catch (DateTimeParseException e) {
            spFecha_cad.setForeground(new Color(204, 0, 0));
            return false;
        }
        spFecha_cad.setForeground(new Color(48, 170, 63));
        return true;
    }

    public boolean comprobarCsv() {
        try {
            if (txtCsv.getText().length() != 3) {
                spCsv.setForeground(new Color(204, 0, 0));
                return false;
            }

            csvTarjeta = Integer.parseInt(txtCsv.getText());
        } catch (NumberFormatException e) {
            spCsv.setForeground(new Color(204, 0, 0));
            return false;
        }

        spCsv.setForeground(new Color(48, 170, 63));
        return true;
    }

    public boolean comprobarPin() {
        try {
            if (txtPin.getText().length() != 6) {
                spPin.setForeground(new Color(204, 0, 0));
                return false;
            }

            int num = Integer.parseInt(txtPin.getText());

        } catch (NumberFormatException e) {
            spPin.setForeground(new Color(204, 0, 0));
            return false;
        }

        spPin.setForeground(new Color(48, 170, 63));
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detras = new recursos.LookVentana.PanelGlowingGradient();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        txtCsv = new javax.swing.JTextField();
        spCsv = new javax.swing.JSeparator();
        txtPin = new javax.swing.JTextField();
        spPin = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        delante = new recursos.LookVentana.PanelGlowingGradient();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        spNumero = new javax.swing.JSeparator();
        txtFecha_cad = new javax.swing.JTextField();
        spFecha_cad = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(49, 51, 53));

        detras.setBackgroundLight(new java.awt.Color(21, 21, 21));
        detras.setPreferredSize(new java.awt.Dimension(560, 293));
        detras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        lblTitulo2.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo2.setText("JasonBet");

        txtCsv.setEditable(false);
        txtCsv.setBackground(detras.getBackground());
        txtCsv.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtCsv.setForeground(new java.awt.Color(255, 255, 255));
        txtCsv.setText("123");
        txtCsv.setBorder(null);
        txtCsv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCsvFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCsvFocusLost(evt);
            }
        });

        spCsv.setBackground(detras.getBackground());
        spCsv.setForeground(new java.awt.Color(255, 255, 255));

        txtPin.setEditable(false);
        txtPin.setBackground(detras.getBackground());
        txtPin.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtPin.setForeground(new java.awt.Color(255, 255, 255));
        txtPin.setText("123456");
        txtPin.setBorder(null);
        txtPin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPinFocusLost(evt);
            }
        });

        spPin.setBackground(detras.getBackground());
        spPin.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PIN:");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CSV:");

        javax.swing.GroupLayout detrasLayout = new javax.swing.GroupLayout(detras);
        detras.setLayout(detrasLayout);
        detrasLayout.setHorizontalGroup(
            detrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detrasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(detrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCsv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spCsv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spPin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addGroup(detrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detrasLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detrasLayout.createSequentialGroup()
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(detrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(detrasLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel2)
                    .addContainerGap(447, Short.MAX_VALUE)))
        );
        detrasLayout.setVerticalGroup(
            detrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detrasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(txtCsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(spCsv, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(detrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(detrasLayout.createSequentialGroup()
                        .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(spPin, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(detrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(detrasLayout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(jLabel2)
                    .addContainerGap(135, Short.MAX_VALUE)))
        );

        spCsv.setVisible(false);
        spCsv.setVisible(false);

        delante.setBackground(new java.awt.Color(21, 21, 21));
        delante.setBackgroundLight(new java.awt.Color(21, 21, 21));
        delante.setGradientColor1(new java.awt.Color(0, 69, 255));
        delante.setGradientColor2(new java.awt.Color(255, 0, 0));
        delante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delanteMouseClicked(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("JasonBet");

        lblNombre.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Jason Young Pena");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Pantalla/chip (1).png"))); // NOI18N

        txtNum.setEditable(false);
        txtNum.setBackground(delante.getBackground());
        txtNum.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        txtNum.setForeground(new java.awt.Color(255, 255, 255));
        txtNum.setText("1111   1111   1111   1111");
        txtNum.setBorder(null);
        txtNum.setPreferredSize(new java.awt.Dimension(340, 40));
        txtNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumFocusLost(evt);
            }
        });

        spNumero.setBackground(delante.getBackground());
        spNumero.setForeground(new java.awt.Color(255, 255, 255));

        txtFecha_cad.setEditable(false);
        txtFecha_cad.setBackground(detras.getBackground());
        txtFecha_cad.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtFecha_cad.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha_cad.setText("01/01");
        txtFecha_cad.setBorder(null);
        txtFecha_cad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFecha_cadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFecha_cadFocusLost(evt);
            }
        });

        spFecha_cad.setBackground(delante.getBackground());
        spFecha_cad.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout delanteLayout = new javax.swing.GroupLayout(delante);
        delante.setLayout(delanteLayout);
        delanteLayout.setHorizontalGroup(
            delanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delanteLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(delanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delanteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(delanteLayout.createSequentialGroup()
                        .addGroup(delanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(delanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(delanteLayout.createSequentialGroup()
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(delanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spFecha_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFecha_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(spNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(140, Short.MAX_VALUE))))
        );
        delanteLayout.setVerticalGroup(
            delanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delanteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(spNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(delanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(delanteLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtFecha_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(spFecha_cad, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        requestFocusInWindow(false);
        spNumero.setVisible(false);
        spFecha_cad.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(delante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(delante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        detras.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumFocusGained
        spNumero.setForeground(new Color(0, 153, 255));

        if (txtNum.getText().equalsIgnoreCase("1111   1111   1111   1111")) {
            txtNum.setText("");
        }
    }//GEN-LAST:event_txtNumFocusGained

    private void txtNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumFocusLost
        spNumero.setForeground(new Color(255, 255, 255));

        if (txtNum.getText().isBlank()) {
            txtNum.setText("1111   1111   1111   1111");
        } else {
            comprobarNumero();
        }
    }//GEN-LAST:event_txtNumFocusLost

    private void txtFecha_cadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFecha_cadFocusGained
        spFecha_cad.setForeground(new Color(0, 153, 255));

        if (txtFecha_cad.getText().equalsIgnoreCase("01/01")) {
            txtFecha_cad.setText("");
        }
    }//GEN-LAST:event_txtFecha_cadFocusGained

    private void txtFecha_cadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFecha_cadFocusLost
        spFecha_cad.setForeground(new Color(255, 255, 255));

        if (txtFecha_cad.getText().isBlank()) {
            txtFecha_cad.setText("01/01");
        } else {
            comprobarFecha();
        }
    }//GEN-LAST:event_txtFecha_cadFocusLost

    private void txtCsvFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCsvFocusGained
        spCsv.setForeground(new Color(0, 153, 255));

        if (txtCsv.getText().equalsIgnoreCase("123")) {
            txtCsv.setText("");
        }
    }//GEN-LAST:event_txtCsvFocusGained

    private void txtCsvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCsvFocusLost
        spCsv.setForeground(new Color(255, 255, 255));

        if (txtCsv.getText().isBlank()) {
            txtCsv.setText("123");

        } else {
            comprobarCsv();
        }
    }//GEN-LAST:event_txtCsvFocusLost

    private void txtPinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPinFocusGained
        spPin.setForeground(new Color(0, 153, 255));

        if (txtPin.getText().equalsIgnoreCase("123456")) {
            txtPin.setText("");
        }
    }//GEN-LAST:event_txtPinFocusGained

    private void txtPinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPinFocusLost
        spPin.setForeground(new Color(255, 255, 255));

        if (txtPin.getText().isBlank()) {
            txtPin.setText("123456");

        } else {
            comprobarPin();
        }
    }//GEN-LAST:event_txtPinFocusLost

    private void delanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delanteMouseClicked
        delante.setVisible(false);
        detras.setVisible(true);
    }//GEN-LAST:event_delanteMouseClicked

    private void detrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detrasMouseClicked
        delante.setVisible(true);
        detras.setVisible(false);
    }//GEN-LAST:event_detrasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private recursos.LookVentana.PanelGlowingGradient delante;
    private recursos.LookVentana.PanelGlowingGradient detras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JSeparator spCsv;
    private javax.swing.JSeparator spFecha_cad;
    private javax.swing.JSeparator spNumero;
    private javax.swing.JSeparator spPin;
    private javax.swing.JTextField txtCsv;
    private javax.swing.JTextField txtFecha_cad;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtPin;
    // End of variables declaration//GEN-END:variables
}
