package vista;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.ImageIcon;
import modelo.DAO;

/**
 *
 * @author xDoble_Jx
 */
public class VMain extends javax.swing.JFrame {

    private int posX, posY;
    private DAO dao;

    /**
     * Creates new form VMain
     */
    public VMain(DAO dao) {
        this.dao = dao;

        initComponents();

        setBackground(new Color(0, 0, 0, 0));

        setIconImage(new ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/logo.png")).getImage());

        BarraTareas.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                posX = e.getX();
                posY = e.getY();
            }
        });

        BarraTareas.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent e) {
                int dx = e.getX() - posX;
                int dy = e.getY() - posY;
                setLocation(getLocation().x + dx, getLocation().y + dy);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new recursos.LookVentana.RoundPanel();
        BarraTareas = new recursos.LookVentana.RoundPanel();
        bntCerrar = new javax.swing.JButton();
        loginAndRegister1 = new vista.LoginAndRegister();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        roundPanel1.setBackground(new java.awt.Color(21, 21, 21));

        BarraTareas.setBackground(new java.awt.Color(102, 102, 102));
        BarraTareas.setMinimumSize(new java.awt.Dimension(100, 25));
        BarraTareas.setPreferredSize(new java.awt.Dimension(28, 25));

        bntCerrar.setBackground(BarraTareas.getBackground());
        bntCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos_Pantalla/btnCerrar.png"))); // NOI18N
        bntCerrar.setBorder(null);
        bntCerrar.setBorderPainted(false);
        bntCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraTareasLayout = new javax.swing.GroupLayout(BarraTareas);
        BarraTareas.setLayout(BarraTareasLayout);
        BarraTareasLayout.setHorizontalGroup(
            BarraTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraTareasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntCerrar)
                .addContainerGap())
        );
        BarraTareasLayout.setVerticalGroup(
            BarraTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraTareasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraTareas, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(loginAndRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addComponent(BarraTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(loginAndRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bntCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private recursos.LookVentana.RoundPanel BarraTareas;
    private javax.swing.JButton bntCerrar;
    private vista.LoginAndRegister loginAndRegister1;
    private recursos.LookVentana.RoundPanel roundPanel1;
    // End of variables declaration//GEN-END:variables

    public void iniciarSesion() {
        VPrincipal vPrincipal = new VPrincipal(this, true, dao);
        this.setOpacity(0);
        vPrincipal.setVisible(true);
    }
}
